pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm i'
            }
        }
        stage('Verification') {
            steps {
                parallel(
                    "testing": {
                        sh 'npm run test-cov'
                    },
                    "linting": {
                        sh 'npm run lint'
                    }
                )
            }
        }
        stage('Publish') {
            when { branch 'master' }
            steps {
                sh 'docker build -t <%= dockerRegistryPrefix %><%= dockerContainerName %>:latest .'
                sh 'docker push <%= dockerRegistryPrefix %><%= dockerContainerName %>:latest'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'coverage/lcov-report/**/*', fingerprint: true
        }
    }
}
